#! /usr/bin/bash

sxhkd -c "$XDG_CONFIG_HOME/bspwm/sxhkdrc" &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#888888"
bspc config normal_border_color "#444444"

# why do you have to be like this, emacs?
bspc rule -a Emacs state=tiled

setxkbmap -layout us,it -option grp:win_space_toggle
feh --bg-center ~/Pictures/wallpapers/blackstar-fuck.png

# top bar
polybar &

# dock
bspc rule -a tint2 layer=top
tint2 ~/stolen-dotfiles/king-byte/tint2/panellauncher.tint2rc &
~/.config/bspwm/bar-thing & # sets bottom padding to 0 after tint2 hides
